List allArticles = [
  [
    "Emotech: An AI assistant with personality",
    "Smita Sen",
    "1si20cs110",
    "assets/images/emotech.jpg",
    """'Hey Olly, play me some smooth jazz'. Yes, I am saying olly not Alexa . You must have heard about Alexa more commonly than olly but the question is how olly is different from Alexa. Olly will do some autopiloting of your lifestyles needs as it gets to know you better and learns your habits. Olly is a doughnut-shaped speaker with a voice assistant that evolve and adapt your personality. so, whatever, I have mentioned above sounds interesting ,right ? Let's explore it.

Once olly get to know what you want to achieve ,what kind of lifestyle you want, your preferences, your daily routines then it will evolve its personality based on yours. It simply means that your olly will be different to my olly because your personality is different to mine and your lifestyle is different. That is why the title of this article is "an AI assistant with personality". The underlying OS for Olly is based on Android. Who owns the idea of olly? Emotech, a London based start-up, that specializes in AI technology and works on exploring emotions in robot using artificial intelligence. Emotech was founded in 2014,london,UK. Emotech dreamed to develop the world's first robot named olly with unique personality. Emotech headed to The Data Lab for its support and secured funding allowing them to collaborate with Heriot-Watt University on the project, undertake the required research and develop the test models. Olly can give you shock with its amazing tasks like playing music, dimming lights, writing emails and setting alarms. Olly takes it to next level through its ability to understand and generate language, allowing it to remember specific user requests and anticipate needs. In terms of how the device works, it will listen continually for a voice trigger command before sending any voice data to its cloud platform for processing. So the co-founders claim it won’t be harvesting and data-mining your private conversations only recording the stuff you’re directing at it.

Olly can also detect a face and take a photo to upload to the cloud for future reference . It can also turn physically to face the person speaking to it. “Through face and voice recognition, Olly knows who is the direct owner, but Olly cannot tell who is the guest,” adds Chen, co-founder of emotech.She says the process of introducing new people to Olly can be controlled by the direct owner and will be like a real friends introduction — so the owner can presumably say, 'Olly this is my friend Gemma' and the bot will record the name and a photo of the person’s face for future reference. Is olly portable? yes, Olly is designed to be more portable than rival devices. You can carry it around the house . So it will have a built-in battery which they say will be good for some eight hours of operational time. Whether people will really want to carry a digital eyeball around the house with them remains to be seen. Cost wise, they’re not fixed on a retail price point yet but Chen suggests Olly will be in the region of £200 to £300. Now the question is what happened to olly? olly still isn't finished though, and the company can't say when it will finish . Emotech switched to a software-licensing model that created the first multimodal AI English teaching assistant using olly brain.it will help educators. "It brings authentic pronunciation, higher effectiveness, personalized English learning; and most importantly, affordable. You can find the solution on Huawei Cloud already."

The company hasn't given up on Olly but it needs months to debug everything and deliver the version that Indiegogo backers were promised in 2017. since olly still is not finished most of the backers asked for refund. Chen said it had "finished all the refunding since we don't think we can deliver in upcoming year" and emphasized that "not every backer has asked for refund" as some "would like to wait and go through the journey with us".For now it's not clear if or when that journey will end.""",
  ],
  [
    "Robotic Process Automation",
    "Karanam Sree Harika",
    "1SI20CS044",
    "assets/images/RoboticProcessAutomation.png",
    """Before computers came into existence, humans used to do all the work with the facilities available. After the computers came into the picture, things were made easy and calculations became possible just by one mouse click. But here, there is a need for humans to operate a system. But now, with the help of new technology RPA(Robotic Process Automation), we can just say the computer instructions of task so that it can perform on its own.

Robotic Process Automation is an ever-evolving technology that follows the same way humans interact with the computer to perform most repetitive tasks. RPA technology creates bots that can complete tasks and sending replies to messages. For example, in the medical department, it is very difficult to maintain the records of all patients it takes much time to go through all the data and is very difficult to sort out but with the help of Robotic Process Automation is very easy to sort out the details within minutes. The system can read the characters in the files and gives out the correct information that we wanted. There are many advantages of Robotic Process Automation: • Improves efficiency • Reduces cost by reducing manual work • Making customer services better • Reduces repetitive tasks • Increases the speed of processing time Robotic Process Automation technology is used in many ways. Some of them are as follows: • Health care • Financial services • Transportation • Legal Services • Supply chain • Banking • Telecommunications

Robotic Process Automation is the current buzzword representing the current fast development in the global robotics environment. These are software robots designed to replace human works. Automation is a system that does not involve human interaction. Even though RPA has gained popularity for its simplicity the are some challenges faced by RPA. Some of them are mentioned below: • Bots created with the help of RPA sometimes need to access sensitive information to perform the task. If they are compromised they pose an additional security risk to the firms • Even RPA software bots are easy to implement it is very hard to manage and govern them There are three types of RPA: 1. Attended RPA: Bots are invoked by a user. Used by customer-facing functions like customer services. 2. Unattended RPA: Bots that perform tasks in batches based on automatic triggers. 3. Hybrid RPA: A combination of both.

If you are part of a business that depends on any repetitive tasks you must get to know about RPA. Because RPA bots can take on boring repetitive tasks and can perform better with few errors compared to humans. Implementing RPA can increase the company’s efficiency and also improves customer experience by allowing employees to do meaningful tasks. RPA improves efficiency. Repetitive tasks can be accomplished effectively. So that humans can focus on human-centric strengths such as reasoning etc."""
  ],
  [
    "ICT Automation",
    "Sinchana K M",
    "1si20cs109",
    "assets/images/ICTAutomation.jpg",
    """Automation ict (information and communication technology) it is the process of creating software and system to replace repetable process and reduce manual intervention. It is one of the major indispensable tool in the world. It is most infrastructure and components that enable modern computing. Now so many business are turning virtual in one another way, people are depending on to carry our operation.

The word automation is derived by the Greek word which means “the technique of making apparatus” and it is used to donate the “process of following a predetermined sequence of operation with little or no human labour using specialized equipment and device”. From the day when punching machine were considered cutting edge technology to today's electronics bar code scanner, technology in infrastructure has come a long way indeed technology then consisted mainly of mechanical equipment with human involvement and supervision but today because automation without human involvement infrastructure are produced with better accuracy and efficiency. we use automation in day to day life like in kitchen tool, automobiles, FAST tags, agriculture, medical, sports, education, escalator, entertainment , industrial machinery and so on.

There is lot of future for ict automation. There is lots of pros and cons in automation but pros overcome cons . The major benefits of automation are reducing operation cost, increasing productivity, ensuring high availability , increasing reliability, optimizing performance etc. automation system imbued with AI insights theoretically lessen the important of deliberation , human made automation rules , relying instead on autonomous choices guided by high-level business cost and complains requirements. Ict automation platform are likely to relay heavily on artificial learning technologies.

There has been remarkable progress in automation since its envisioning by engineers in the middle of 12th century and it has come with benefits as well as challenges and limitation. Today , automation can perform very complex tasks, resulting in high volume of quality products at low cost with minimal or no accidents. Its implementation is however ,encumbered by the high initial cost of setting up. It may increase labour unemployment. however, there are more advantage in automation ict."""
  ],
  [
    "Tactile VR",
    "Aprajita Priya",
    "1SI19CS016",
    "assets/images/TactileVR.jpg",
    """VR i.e Virtual Reality is the use of computer technology to create a simulated environment.'VR Tactile' is a haptic digital architectural environment that combines physical materiality with digital information to create a multi-sensory, interactive experience.It implies a complete immersion experience that shuts out the physical world.The first virtual reality headset was created in 1968 by American computer scientist Ivan Sutherland and his student, Bob Sproull.

Virtual Reality (VR) technology utilises visual and auditory senses to allow users to experience and create immersive and dynamic virtual environments. However this space lacks the sense of touch, isolating the user to a completely computer generated reality. In contrast, although architecture has rarely been dynamic or interactive, buildings use tactile materials to augment the spatial experience within these spaces. 'Tactile VR' is a project that combines these two realities together to explore the concept of tangible data. Through the installation users can engage with a new type of architectural space, where the tactility of physical architecture is merged with dynamic digital spatial configuration. There are 3 primary categories of virtual reality simulations used today: non-immersive, semi-immersive, and fully-immersive simulations. Non-immersive virtual reality is a type of virtual reality in which you interact with a virtual environment usually through a computer where you can control some characters or activities within the experience, but the virtual environment is not directly interacting with you.A good example of non-immersive virtual reality would be a computer game like Dota 2. You can control aspects of your character and they will have an effect on the virtual environment of the game. Technically you are interacting with a virtual environment but not directly. Your character in the game does that.

Fully immersive virtual reality is the opposite of non-immersive virtual reality. It ensures a realistic virtual experience. It would feel as if you are physically present in the virtual world and the events occurring there are happening to you.Special equipment like VR glasses, gloves, body detectors equipped with sense detectors is required to provide a realistic virtual experience. The data from these sensors is used by the computer and the virtual world responds to that in real-time to provide users with a realistic virtual experience.An example of this would be a Virtual Gaming Zone, where using special gear you and other players can interact with the virtual environment, all at the same time, and play with or against each other.A semi-immersive virtual reality is something in between non-immersive and fully immersive virtual reality. Using a computer screen or VR glasses, you can move around in a virtual environment but other than your visual experience you will have no physical sensations to enhance the experience.A virtual tour can be a good example of semi-immersive virtual technology. It can be device-based or web-based. Many businesses are opting for this technology as participants can roam around the place without having to be there physically.

VR will diversely enrich and revolutionize our world. It offers new possibilities to understand and experience history, cities or landscapes.In every generation, there is a technology that defines them.For our parents, it was the internet.For us,it is the iPhone.For the next generation it will be virtual reality.Learning,entertainment,Shopping, human interaction, intimacy is and will all be influenced in some form by virtual reality. Thus virtual reality positively impress us in all aspects."""
  ],
];

// [title, name, usn, image, text]